name: Acceso a la fortaleza

on: 
  workflow_dispatch:

jobs:
  acceso-a-la-base:
  runs-on: ubunto-latest
  
  steps:
      - name: El agente llega a la fortaliza
        run: |
          echo "Agente {{github.actor}} llega a la fortaleza" 
          echo ""
          echo "buscar los archivos de la legion "
          ls -la
          echo ""
          echo "pero que paso? no hay nada"

      - name: "Brainaic desbloquea"
        uses: actions/checkout@v4 

      - name: ahora si ver los panes
        run: |
          echo "Agente {{github.actor}} llega a la fortaleza" 
          echo ""
          echo "buscar los archivos de la legion "
          ls -la
          echo "funciona"
          echo ""
          echo "Planes:"
          echo "villanoes:"
          ls villanos/
          echos "Inteligencia:"
          ls inteligencia/
