# This is a basic workflow to help you get started with Actions

name: Cominocador de la legion

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      villano:
        description: "que villano envia el mensaje?"
        required: true
        type: choice
        options:
          - lex luthor
          - Magneto
          - Joker
          - Mystique
          - Brainian

      mensaje:
        description: "Mensaje para el consejo"
        required: true
        default: "la mision fue un exito"

      prioridad:
          description: "Nivel de prioridad"
          required: true
          type: choice
          options:
            - Normal
            - Alta
            - Critica



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  transmitir-mensaje:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Imprimir inputs
        run: |
          echo "imputs:"
          echo " "
          echo "villano: ${{inputs.villano}}"
          echo "villano: ${{inputs.mensaje}}"
          echo "villano: ${{inputs.prioridad}}"


